---
application_name: 'tester'
namespace: 'testernamespace'
docker_registry:
  url: <%= ENV['DOCKER_REGISTRY_URL'] %>
  user: <%= ENV['DOCKER_REGISTRY_USER'] %>
  password: <%= ENV['DOCKER_REGISTRY_PASS'] %>
  email: <%= ENV['DOCKER_REGISTRY_EMAIL'] %>
  namespace: <%= ENV['DOCKER_NAMESPACE'] %>
docker:
  docker_file: './dockerfile/tester/'
  compose_file: './dockercompose/tester/docker-compose.yml'
  build:
    docker_file: './dockerfile/build/'
run:
  consul_loader:
    enabled: true
    config_file: './consul_keys.yml'
    url: <%= "http://#{ENV['DOCKER_IP']}:9500" %>
cucumber:
  consul_loader:
    enabled: true
    config_file: './consul_keys.yml'
    url: <%= "http://#{ENV['DOCKER_IP']}:9500" %>
  health_check:
    enabled: true
    url: <%= "http://#{ENV['DOCKER_IP']}:8080/health" %>
after_build:
  copy_assets:
    -
      from: '../target/tester-0.0.1-SNAPSHOT.jar'
      to: './dockerfile/tester'
