source 'https://rubygems.org'

gem "rake"
gem 'cucumber-api', '~> 0.3'
gem 'nokogiri'

gem 'minke'
gem 'minke-generator-spring', :git => 'git@github.com:notonthehighstreet/minke-generator-spring.git'
